### ISSUE TITLE
Sniffles joint calling 

### ISSUE THREAD

**Issue by minw2828** [PacificBiosciences/HiFi-somatic-WDL#3]
Hello Khi,

I hope you are well. 

I am a postdoc with Sean at umccr. We had a sequencing and analysis done with you in 2023. I wanted to follow up with you about sniffles.

The joint-calling of sniffles appeared to be run per individual, not per cohort. I am wondering if you found jointing calling on normal and tumour tissues more beneficial than the entire cohort. 

Many thanks,
Min

**Comment by minw2828** [comment]
Hi Khi, 

May I also ask about the naming conventions of the sequencing files, please? 

We received a uBAM file named `<individual_id>.normal/m84039_230813_021121_s2.hifi_reads.default.bam`. What does `m84039_230813_021121_s2` denote? 

Many thanks,
Min

**Comment by proteinosome** [comment]
Hi Min, good to hear from you! Feel free to reach out to me directly via my email at kpin@pacb.com too, as we have a close collaboration and I might respond faster there.

To your question: We no longer use Sniffles in the latest pipeline. The current version uses Severus and calls tumor vs normal. On the question of using a full cohort: It could be useful to remove common germline SVs if you have a large enough cohort. The current callset is already filtered against the HPRC healthy cohort (~100 samples) so a lot of the common germline SVs are already filtered out. I would imagine however there's potentially some local ethnicities-specific SVs that are not in the HPRC cohort (which is small by any population seq standard, but useful nonetheless) that remains in there, and a cohort-based joint calling approach can be useful.
