### ISSUE TITLE
Sample name in the title of the report

### ISSUE THREAD

**Issue by byoo** [PacificBiosciences/HiFi-somatic-WDL#7]
I'd like to report that the "sample_name" in the title of the report is empty, though the parameter, sample_name, is passed as expected.
It appears that either this code below didn't work or the container has the report file that doesn't display the sample name properly.

https://github.com/PacificBiosciences/HiFi-somatic-WDL/blob/07a1799b2506d533da53a4dc4155960c721db7b7/containers/somatic_r_tools/visualize_hifisomatic.qmd#L2

**Comment by proteinosome** [comment]
Thanks @byoo . The report will likely go through a major visualization update in the next iteration so I'm going to hold on fixing this for now.
