### ISSUE TITLE
Missing example file, input.example.json.

### ISSUE THREAD

**Issue by mgladsto** [PacificBiosciences/HiFi-somatic-WDL#9]
At this page https://github.com/PacificBiosciences/HiFi-somatic-WDL/blob/main/docs/step-by-step.md#modify-the-input-json-file-to-point-to-the-downloaded-files

there is a link to an example input json but the link is dead https://github.com/PacificBiosciences/HiFi-somatic-WDL/blob/main/docs/example_configs/input.example.json

**Comment by proteinosome** [comment]
Fixed. Thanks.

**Comment by mgladsto** [comment]
File is still not found on my end.
